### ISSUE TITLE
Style warning when matching structs on SBCL.

### ISSUE THREAD

**Issue by marcoheisig** [guicho271828/trivia#104]
The following snippet of code produces a weird style warning on SBCL.  (Both on 1.4.5 and 1.4.15):
```lisp
(in-package #:cl-user)

(defstruct (foo (:predicate foop)))

(trivia:defpattern foo ()
  (let ((it (gensym)))
    `(trivia:guard1 ,it (foop ,it))))

(defun foo-finder (x)
  (trivia:match x
    ((foo) (format t "Found a foo!"))))

```

The style warning is

> ; in: defun foo-finder
> ;     (TRIVIA.LEVEL2:MATCH X
> ;       ((FOO) (FORMAT T "Found a foo!")))
> ; --> TRIVIA.LEVEL2:MATCH2 TRIVIA.LEVEL2:MATCH2+ 
> ; ==>
> ;   (TRIVIA.LEVEL2:MATCH2*+ (X)
> ;       (T)
> ;     (((FOO)) (FORMAT T "Found a foo!"))
> ;     ((TRIVIA.LEVEL2.IMPL::_) NIL))
> ; 
> ; caught style-warning:
> ;   undefined type: (foo)
> ; 
> ; compilation unit finished
> ;   Undefined type:
> ;     (foo)
> ;   caught 1 STYLE-WARNING condition

I only get this style warning with the latest Trivia release on Quicklisp, so it must have been due to a recent change.

**Comment by guicho271828** [comment]
* I can reproducible this on SBCL 1.5.5
* You can find the source of this condition on the debugger by `(setf *break-on-signals* t)` and continue (i.e. ignore))) the first signal.
* The error comes from `type-i:all-compound-types`, which is a function that tries to enumerate all possible type specifier for an atomic type specifier.  For example `foo` is a valid typespec then `(foo)` is also a valid typespec, while `(foo *)` is not a valid typespec. In constrast `array`, `(array)`, `(array *)` `(array * *)` are all valid typespecs. The function heuristically tries to catch when to stop adding `*`s to the type specifier.  https://github.com/guicho271828/type-i/blob/master/src/infer-typep.lisp#L39 See comments in the source code.
* It seems during the compile time the error is converted into a style warning.
* Trivia switched to balland2006 optimizer recently, which makes it depend on `type-i`. So yes, your analysis is correct.

**Comment by marcoheisig** [comment]
Here we go: https://github.com/guicho271828/type-i/pull/2.

**Comment by guicho271828** [comment]
merged. thanks!
