### ISSUE TITLE
Trivia's atrophied on ABCL

### ISSUE THREAD

**Issue by remexre** [guicho271828/trivia#105]
Check the latest Travis results (e.g. [#438.5](https://travis-ci.org/guicho271828/trivia/jobs/587343282)) to see an `UNBOUND-VARIABLE` on load.

It might be a better solution to disable the CFFI tests for ABCL with `#-abcl` than to allow failures in general.

**Comment by remexre** [comment]
It looks like this is because `trivial-cltl2` assumes ABCL exports all the relevant symbols from the `lisp` package, when in fact it only exports `compiler-let`.

**Comment by guicho271828** [comment]
hmm, I am not particularly fond of hiding test failures. I think allowing failures is a better option, assuming that ABCL will eventually implement other cltl2 functions.

**Comment by remexre** [comment]
I mean, right now the tests are failing, just silently; I'm just suggesting limiting the scope of what's ignored.

I'm not sure what the timeline on ABCL getting these functions looks like; https://github.com/armedbear/abcl/issues/87 exists but is closed.

I'm not familiar enough with this codebase to know, would it be practical to change `#-(or ecl)` to `#-(or abcl ecl)` [here](https://github.com/guicho271828/trivia/blob/master/level2/impl.lisp#L364) and [here](https://github.com/guicho271828/trivia/blob/master/level2/impl.lisp#L378)? I tried it in [my fork](https://github.com/remexre/trivia), and it looks like it works (at the level of testing I could do during lunch); I can PR it if you want.

**Comment by guicho271828** [comment]
> change #-(or ecl) to #-(or abcl ecl) here and here? 

oh that makes sense. Sure, send me a PR.

**Comment by remexre** [comment]
Just opened https://github.com/guicho271828/trivia/pull/106; are you open to reworking testing so a regression here fails the Travis build?

**Comment by guicho271828** [comment]
CFFI seems to work on abcl after disabling the cltl2 part.
