### ISSUE TITLE
Exponential time for match compilation

### ISSUE THREAD

**Issue by pfdietz** [guicho271828/trivia#108]
The time to compile a MATCH form can increase exponentially with the depth of the pattern.  The attached file shows the issue.    (try 8) takes nearly an order of magnitude longer than (try 7).  

[example2.lisp.gz](https://github.com/guicho271828/trivia/files/3703503/example2.lisp.gz)

**Comment by pfdietz** [comment]
Simply compiling the pattern (list (list (list ... (list x) ...))) in a match takes exponential time in the depth of nesting.

**Comment by guicho271828** [comment]
you can fall back to the simpler compiler by `(declare (trivia:optimizer :trivial))`. does it still have the same behavior?

**Comment by pfdietz** [comment]
I tried that (on the first example there).   It did not fix the problem.  The time seems to be being spent in "repair", which has something to do with or patterns?

**Comment by guicho271828** [comment]
Ah, "repair" is used to check & fix the disjunctives (ORs) in order to ensure that each branch of OR has the same set of variables. Yes, the algorithm has a room for improvement, it is currently implemented quite naively.

**Comment by pfdietz** [comment]
In more detail, in sbcl:

(sb-cltl2:macroexpand-all '(match (x) ((list (list (list ... (list y) ...))) y)))

when profiled shows most of the time is being spent under TRIVIA.LEVEL1:CORRECT-PATTERN, and also TRIVIA.LEVEL1:VARIABLES.   What's sad here is that the pattern doesn't have any OR in it, so all the work is being done for nothing.

**Comment by pfdietz** [comment]
Attaching a memoization patch that greatly reduces the time growth rate.

[trivia.exp-time.patch.gz](https://github.com/guicho271828/trivia/files/3709237/trivia.exp-time.patch.gz)

**Comment by guicho271828** [comment]
will probably check in the weekends, thanks!

**Comment by pfdietz** [comment]
That's not necessarily the best patch -- the time spent hashing the large keys could probably be reduced -- but it's a lot faster than exponential time.

**Comment by guicho271828** [comment]
Tested the patch, I don't find any problem in the code. 

It dramatically reduced the compile time of [type-r](https://github.com/guicho271828/type-r) library which parses the CL type specifier with complex patterns --- from 21sec to 2.5 sec!

Thanks for contributing the code. I looked up the internet to find your contact address. Do you mind using the university address from U. Rochester (found in the persistent array paper)? Thank you.

**Comment by pfdietz** [comment]
No, that's an old and dead email address.  Reach me at paul.f.dietz@gmail.com

**Comment by guicho271828** [comment]
merged into master. Thank you very much!
