### ISSUE TITLE
setf-ing objects with let-match[1]

### ISSUE THREAD

**Issue by digikar99** [guicho271828/trivia#111]
Is this a bug or working-as-designed?

```lisp
CL-USER> (defstruct foo slot-1)
FOO
CL-USER> (defparameter f (make-foo))
F
CL-USER> (trivia:let-match1 (foo slot-1) f (setf slot-1 2))
2
CL-USER> (foo-slot-1 f)
NIL
CL-USER> (with-slots (slot-1) f (setf slot-1 2))
2
CL-USER> (foo-slot-1 f)
2
```

If working-as-designed, are there issues making `let-match1` behave compatibility with `with-slots` or any design decisions?

Thanks!

**Comment by guicho271828** [comment]
You should use the place pattern

**Comment by guicho271828** [comment]
(foo :slot-1 (place slot-1)) or (foo (slot-1 (place slot-1)))

**Comment by digikar99** [comment]
Thanks! I have editted the [entry on Special Patterns](https://github.com/guicho271828/trivia/wiki/Various-Patterns/08c0ba313dfd752252283fb1ef296224bcf4024e) to include the mention of `place` pattern. (Found the wiki page mention from the cookbook.)
