### ISSUE TITLE
Symbol is unbound in namespace pattern 

### ISSUE THREAD

**Issue by charJe** [guicho271828/trivia#142]
This error seems to only happen when the file is compiled with asdf. It does not happen if the file is loaded with `load`. If `get-bar` is moved to another file that is compiled after, there is no error.

```lisp
(defclass foo ()
  ((bar
    :initarg :bar
    :reader bar)))

(defmethod get-bar (thing)
  (ematch thing
    ((foo :bar bar)
     bar)))
```

```lisp
; in: defmethod get-bar
;     (TRIVIA.LEVEL2:EMATCH THING
;       ((FOO :BAR BAR)
;        BAR))
; 
; caught error:
;   (during macroexpansion of (sb-pcl::%defmethod-expander get-bar ...))
;   Symbol foo is unbound in namespace pattern
```

**Comment by guicho271828** [comment]
You must wrap defclass in eval-when

**Comment by charJe** [comment]
That seems like more of a work around. Is there a better solution?

**Comment by charJe** [comment]
I see. That is unfortunate.

**Comment by charJe** [comment]
I was just looking at `find-class` and saw that it has an environment parameter. I didn't see a way to use it for sensing compiled `defclass` forms though. 😿
