### ISSUE TITLE
PPCRE matcher to work on symbols

### ISSUE THREAD

**Issue by PuercoPop** [guicho271828/trivia#26]
Hi,
  This is a feature request. Currently the ppcre matcher only works on literal strings, would it be possible to treat symbols as potential variables?

For example

```lisp
(let ((url-regexp "^/user/(\\w+/$)"))
  (match "/user/1/"
    ((ppcre url-regexp user-id) user-id)))
```

complains that url-regexp is not of type string. Being able to associate regexps with names that describe their intent is useful from a development experience point of view, even if at odds with efficiency.

**Comment by guicho271828** [comment]
Interesting point. I will consider adding the suggested feature. In fact, the ppcre matcher is (in both optima and trivia) very much UNsophisticated/optimized, and there is plenty room for improvement.

**Comment by guicho271828** [comment]
#27

**Comment by guicho271828** [comment]
it will work on forms, not only symbols.

**Comment by PuercoPop** [comment]
Thanks for the prompt implementation of the feature!
