### ISSUE TITLE
Fare quasiquote support?

### ISSUE THREAD

**Issue by PuercoPop** [guicho271828/trivia#29]
Hi @guicho271828,

I'm what is required for trivia to support integration with [fare-quasiquote](http://quickdocs.org/fare-quasiquote/) in the same way as optima. between as shown [here](http://enthusiasm.cozy.org/archives/2013/07/optima). The [integration](https://gitlab.common-lisp.net/frideau/fare-quasiquote/blob/master/fare-quasiquote-optima.lisp#L34) appears to use optima's extension API that is exclusive to optima instead of the simpler defpattern.

**Comment by guicho271828** [comment]
i woukd start working in a few days

**Comment by guicho271828** [comment]
well, it was a matter of 30+ minutes!

**Comment by guicho271828** [comment]
tell me if there are any uncovered test cases

**Comment by PuercoPop** [comment]
Thanks, I'll let you know if I run into any issues
