### ISSUE TITLE
Add Optima's Extra Functions

### ISSUE THREAD

**Issue by noctuid** [guicho271828/trivia#33]
I think it would be nice to have optima's [extra functions](https://github.com/m2ym/optima/blob/master/src/extra.lisp). Trivia has the lambda-match functions, but I don't see `if-match`, `when-match`, `let-match`, etc. I think `let-match` is especially useful and extends optima to be able to be used in much the same way as [metabang-bind](https://common-lisp.net/project/metabang-bind/user-guide.html).

Taking an idea from metabang bind, it might also be nice to be able to match slots with their accessors. Also, I was wondering if it would be possible to have a `values` pattern or is `multiple-value-match` a necessity?

**Comment by guicho271828** [comment]
okay, it seems to work as is if I copy&paste the source into trivia.

**Comment by noctuid** [comment]
Thank you.

**Comment by guicho271828** [comment]
I missed the latter part of the request.

>Taking an idea from metabang bind, it might also be nice to be able to match slots with their accessors.

[This is already supported.](https://github.com/guicho271828/trivia/wiki/Type-Based-Destructuring-Patterns#class-pattern)

> Also, I was wondering if it would be possible to have a values pattern or is multiple-value-match a necessity?

it is a nontrivial issue. Note that in some cases  `values-list` should be useful.

**Comment by noctuid** [comment]
Maybe I'm just missing it, but they all seem to match the slot name itself as opposed to the name of the accessor. Which would be the equivalent of `with-accessors`?

Yeah I guess in most cases, I could use `values-list` with `let-match`. Thanks.

**Comment by guicho271828** [comment]
> with-accessors
Sorry, this point is poorly documented.
I put a decent amount of effort in class/structure patterns in order to maintain the compatibility to Optima. As you can see in [level2/derived-class.lisp#L266](https://github.com/guicho271828/trivia/blob/master/level2/derived-class.lisp#L266), just put an accessor name and it will be recognized. Mapping a name to a single reader in an unbiguous way, with a support for multiple styles, is quite complex.

**Comment by guicho271828** [comment]
you still have to specify the class name in order to use the feature. however, `standard-object` might just work.

```cl
(defclass a () ((%name :reader name :initarg :x))) ;; <--- reader is NAME
(defun fn (x)
   (match x
      ((class a name) ;; <-- accessor NAME
       (print name))))
(fn (make-instance 'a :x 1))
;; -> 1

(defun wrap (x) (name x)) ;; <--- arbitrary function works
(defun fn (x)
   (match x
      ((class a wrap)
       (print wrap))))
(fn (make-instance 'a :x 1))
;; -> 1
```

**Comment by guicho271828** [comment]
you also have `access` pattern.

https://github.com/guicho271828/trivia/wiki/Special-Patterns#access-pattern

**Comment by noctuid** [comment]
Thanks, that's even nicer than what I'd imagined.
