### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by dfmorrison** [guicho271828/trivia#46]
I've not been able to find anything in the sources dealing with licensing. Have I just not looked in the right place, or is it indeed absent? If so, is the implication that you are happy for any one to use this in any way they choose, or do you have thoughts on how you'd like people not to use it?

**Comment by PuercoPop** [comment]
@dfmorrison It is LLGPL, Lisp Lesser General Public Licence

The license is in the [system definition](https://github.com/guicho271828/trivia/blob/master/trivia.asd#L12)

You can check it at the REPL with
```lisp
(asdf/system:system-licence (asdf:find-system :trivia))
```

**Comment by dfmorrison** [comment]
On Wed, Jul 20, 2016 at 4:33 PM, Javier Olaechea <notifications@github.com>
wrote:
> The license is in the system definition

Oh, darn, I should have known to look there. Thanks!




-- 
Don Morrison <dfm2@cmu.edu>
"Mathematics is the part of physics where experiments are cheap."
      -- Vladimir Arnold, "On teaching mathematics", tr A V Goryunov

**Comment by PuercoPop** [comment]
@dfmorrison NP, thanks for reporting the issue. I've added a License file to make licensing information easier to find.

**Comment by guicho271828** [comment]
thanks
