### ISSUE TITLE
assoc pattern raises a type error when matching

### ISSUE THREAD

**Issue by PuercoPop** [guicho271828/trivia#54]
The following code raises a type error saying 1 is not of type list

```lisp
(trivia:match '(1)
  ((assoc :foo val) (list 'found val)))
```

**Comment by guicho271828** [comment]
that's true... well #53 is not a degradation, I think this should also be fixed.
unfortunately I have to leave home now.
will be fixed soon --- perhaps would you do that? adding handler-bind or something around `assoc`.

**Comment by PuercoPop** [comment]
Yes, this issue was present before #53
