### ISSUE TITLE
Feature request: docstring support for `defun-match`

### ISSUE THREAD

**Issue by sjl** [guicho271828/trivia#66]
It would be nice if `defun-match` could optionally take a docstring and pass it along into the underlying `defun`.  Right now it tries to parse the string as a match clause and errors.

According to the [docs](https://github.com/guicho271828/trivia/wiki/Match-and-Variants#macro-lambda-ecmatch--defun-ecmatch) the clauses in the body are always lists, so it should be possible to distinguish a bare string and treat it separately.

If this is something you're interested in I can make a PR for it.

**Comment by guicho271828** [comment]
Nice point, please send a PR.

**Comment by PuercoPop** [comment]
@guicho271828 So `defun-match` would look something like this

```lisp
(defmacro defun-match (name (arg) &body clauses)
  (multiple-value-bind (clauses declarations docstring)
      (parse-body clauses :documentation t)
    `(defun ,name (,arg)
       ,@(when docstring
           (list docstring))
       ,@declarations
       (match ,arg
         ,@clauses))))
```

The repetition in the definitions of defun-* point to a macrolet to reduce the code repetition, what do you think?

**Comment by guicho271828** [comment]
A function is better, since it works inside the macro definition and is traceable. Easier to debug, too.

**Comment by guicho271828** [comment]
*compared to macrolet

**Comment by sjl** [comment]
The macrolet style would be concise, but does get a bit hairy because you need to handle the different arglists for the vanilla/`*` versions:

```lisp
(macrolet ((define-matcher (macro-name macro-arglist matcher-arglist matcher matcher-form)
             `(defmacro ,macro-name (name ,macro-arglist &body body)
               (multiple-value-bind (clauses declarations docstring)
                   (parse-body body :documentation t)
                 `(defun ,name ,,matcher-arglist
                   ,@(when docstring `(,docstring))
                   ,@declarations
                   (,',matcher ,,matcher-form ,@clauses))))))
  (define-matcher defun-match (arg) (list arg) match arg)
  (define-matcher defun-ematch (arg) (list arg) ematch arg)
  (define-matcher defun-cmatch (arg) (list arg) cmatch arg)
  (define-matcher defun-match* args args match* args)
  (define-matcher defun-ematch* args args ematch* args)
  (define-matcher defun-cmatch* args args cmatch* args))
```

**Comment by guicho271828** [comment]
send me a pr anyways

**Comment by guicho271828** [comment]
thanks for your work
