### ISSUE TITLE
Corner case: (quote (a)) does not compile to (list 'a)

### ISSUE THREAD

**Issue by guicho271828** [guicho271828/trivia#86]
It compiles to `(list a)` instead, and the `eq`-test against the symbol `a` is not performed.

**Comment by guicho271828** [comment]
This was a surprise for me while using Trivia for building an algorithm. However,

```lisp
  (is (eql 3 (match '(1 2 3) ('(1 _ a) a))))
  (is (eql 3 (match #(1 2 3) (#(1 _ a) a))))
```

this behavior has been present in Optima and I will preserve this behavior. I almost got bitten by my own product :)

**Comment by guicho271828** [comment]
I would like to ask someone's opinion... @fare ? I summarized the point below:
https://github.com/guicho271828/trivia/wiki/Known-Differences#extended-semantics-of-constant-patterns

**Comment by fare** [comment]
Uh, shouldn't `(quote (a))` be the same as `'(a)' and thus `(list 'a)` ? If you want non-constant, you should be using fare-quasiquote, it was designed exactly for that: `\`(,a)`. Or if you don't want a special reader, still `(quasiquote ((unquote a))`.

**Comment by fare** [comment]
I can understand why the situation sucks with arrays, though. I blame the CL standard (itself constrained by backward compatibility)

**Comment by guicho271828** [comment]
Thanks. It should be a result of an excessive extrapolation when I implemented the structure/array literal patterns, I clearly didn't think enough. I will fix the commits soon.
