### ISSUE TITLE
Import #:split from :cl-ppcre

### ISSUE THREAD

**Issue by akssri** [guicho271828/trivia#92]
Please change the package definition of ```#:trivia.ppcre``` to, 
```
(defpackage :trivia.ppcre
  (:export :ppcre
           :split
           :split*)
  (:import-from :cl-ppcre :split))
```
This removes symbol conflicts if/when one chooses to use symbols from both ```#:cl-ppcre``` and ```#:trivia.ppcre```.

**Comment by guicho271828** [comment]
I'll consider that.

**Comment by akssri** [comment]
Thanks!
