### ISSUE TITLE
guard/or commutativity

### ISSUE THREAD

**Issue by akssri** [guicho271828/trivia#97]
The patterns guard/or appear to be used in 'commutative sense. For instance, the way I would read the below pattern is "find me variables that aren't x", however currently it returns '(the thing x) because the ```guard1``` gets pushed inside the ```or1```.
```lisp
(match '(the thing x)
  ((guard (or (list 'the _ var) var) (not (eql var 'x))) var))
```

The relevant pattern-expansions are given below,
```lisp
M> (pattern-expand-all '(or (list 'the _ var) var))
(OR1
 (GUARD1 (#:CONS2940 :TYPE CONS) (CONSP #:CONS2940) (CAR #:CONS2940)
  (GUARD1 (#:IT2941 :TYPE (EQL THE)) (EQ #:IT2941 'THE)) (CDR #:CONS2940)
  (GUARD1 (#:CONS2942 :TYPE CONS) (CONSP #:CONS2942) (CDR #:CONS2942)
   (GUARD1 (#:CONS2943 :TYPE CONS) (CONSP #:CONS2943) (CAR #:CONS2943)
    (GUARD1 VAR T) (CDR #:CONS2943)
    (GUARD1 (#:IT2944 :TYPE NULL) (NULL #:IT2944)))))
 (GUARD1 VAR T))
```

```lisp 
M> (pattern-expand-all '(guard (or (list 'the _ var) var) (not (eql var 'x))))
(OR1
 (GUARD1 #:INTERSECTION2947 T #:INTERSECTION2947
  (GUARD1 (#:CONS2946 :TYPE CONS) (CONSP #:CONS2946) (CAR #:CONS2946)
   (GUARD1 (#:IT2948 :TYPE (EQL THE)) (EQ #:IT2948 'THE)) (CDR #:CONS2946)
   (GUARD1 (#:CONS2949 :TYPE CONS) (CONSP #:CONS2949) (CDR #:CONS2949)
    (GUARD1 (#:CONS2950 :TYPE CONS) (CONSP #:CONS2950) (CAR #:CONS2950)
     (GUARD1 VAR T) (CDR #:CONS2950)
     (GUARD1 (#:IT2951 :TYPE NULL) (NULL #:IT2951))))
   #:INTERSECTION2947 (GUARD1 (#:GUARD2945 :DEFERRED (NOT (EQL VAR 'X))) T)))
 (GUARD1 #:INTERSECTION2952 T #:INTERSECTION2952
  (GUARD1 VAR T #:INTERSECTION2952
   (GUARD1 (#:GUARD2945 :DEFERRED (NOT (EQL VAR 'X))) T))))
```
Is this by design ? Could this behaviour be changed ?

**Comment by guicho271828** [comment]
Re: commutativity --- I'm not sure this is the exact thing that is happening.
I think you are expecting that, once a branch of an `or` pattern is matched, it should not backtrack to consider other branches when the guarding failed.

The semantics of `or` is different. `or` represents a nondeterministic decision (as in prolog) and it does backtrack. That's why, after the guard `(eql var 'x)` failed, it reconsiders the second branch of `or`, matches  `var` with `(the thing x)`, then checks  `(not (eq var 'x))` (which is satisfied).

The current design comes from Optima.

I believe you can just write it without the guard pattern as follows. Note that the choice never backtracks to the previous clause.
```
(match '(the thing x)
  ((guard (list 'the _ var) (not (eql var 'x))) var))
  ((guard var               (not (eql var 'x))) var))
```

**Comment by guicho271828** [comment]
oops, the code above has the same error. I now realized that you just need to specify the type of var as a symbol.
```lisp
(match '(the thing x)
  ((guard (or (list 'the _ var)
              (and (symbol) var)) ; (type symbol) also works
          (not (eql var 'x)))
    var))
```

**Comment by guicho271828** [comment]
this is more versatile
```lisp
(match '(the thing x)
           ((guard (or (list 'the _ var)
                       (and var
                            (not (list 'the _ _))))
                   (not (eql var 'x)))
            var))
```

**Comment by akssri** [comment]
Sorry, by 'commutativity' I was referring in particular to how 
``` (guard (or <pat1> ... <patn> ) <pred>)```
is equivalent to
```(or (guard <pat1> <pred>) ... (guard <pat1> <pred>)```

I just found the semantics surprising. I'd have read  ```(guard <pat> <pred>)``` as
- "satisfies ```<pat>``` then satisfies ```<pred>```" as opposed to,
- "satisfies ```<pat>``` such that ```<pred>``` is T"
  
Either way is fine I suppose; are there other cases which could lead to such behaviour with ```guard``` ?

**Comment by guicho271828** [comment]
Here https://github.com/guicho271828/trivia/blob/master/level2/impl.lisp#L334 is the basic `lift` operation implemented in optima for guard patterns. I tried to replicate the behavior as much as possible. honestly it was tricky especially around the combination with `not` pattern. You can observe the struggle from e.g. https://github.com/guicho271828/trivia/blob/master/level2/derived.lisp#L60 .
The operation seems to come from a standard ML programming textbook which I don't know.

**Comment by akssri** [comment]
I've added a note to the wiki page noting this behaviour,
https://github.com/guicho271828/trivia/wiki/Logic-Based-Patterns

Doesn't seem like there are others that might be counter-intuitive.

**Comment by guicho271828** [comment]
I discussed this issue with @marcoheisig and I proposed perhaps the guard pattern should be deprecated / removed or reimplemented.

Currently the `guard` pattern is not implemented based on pure pattern expansion, but by inserting the condition to an additonal meta-field in `guard1` pattern. This is preventing using the balland2006 optimizer as the default compiler strategy. It seems to me like @akssri you are the only person who is actively using `guard` pattern. You can replace guard patterns with a sufficient number of custom conditioning and [`fail/skip/next` macro](https://github.com/guicho271828/trivia/wiki/NEXT-FAIL-SKIP-macro).

**Comment by akssri** [comment]
I mostly use the ```guard1``` schema of applying a predicate to a variable, so these changes shouldn't affect me much. Thanks for letting me know.

**Comment by guicho271828** [comment]
ok

**Comment by guicho271828** [comment]
I refactored the entire guard pattern compilation pass. I also identified a bug/difference from Optima. This is now all corrected, and moreover, it no longer uses the meta-information!
@marcoheisig

**Comment by guicho271828** [comment]
going to merge balland2006 optimizer in a couple of days

**Comment by marcoheisig** [comment]
Wow, this is great news!  Thank you very much for your effort!
